# Autogenerated wrapper script for FindMUS_jll for aarch64-linux-musl-cxx11
export findMUS, findmus_msc

using CompilerSupportLibraries_jll
using MiniZinc_jll
JLLWrappers.@generate_wrapper_header("FindMUS")
JLLWrappers.@declare_executable_product(findMUS)
JLLWrappers.@declare_file_product(findmus_msc)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, MiniZinc_jll)
    JLLWrappers.@init_executable_product(
        findMUS,
        "bin/findMUS",
    )

    JLLWrappers.@init_file_product(
        findmus_msc,
        "share/minizinc/solvers/findmus.msc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
